// Catalogo completo de testigos del coche
const catalogo = [
  {
    "id": "001",
    "nombre": "Check Engine / fallo motor",
    "categoria": "Motor",
    "color": "Ambar",
    "gravedad": "Atencion",
    "significado": "Fallo generico detectado por la centralita del motor",
    "accion": "Revisar con diagnosis OBD2 lo antes posible, puede ser desde algo leve a grave",
    "tipo": "Requiere taller",
    "producto": "",
    "validoPara": "Universal"
  },
  {
    "id": "002",
    "nombre": "Presion de aceite baja",
    "categoria": "Motor",
    "color": "Rojo",
    "gravedad": "Critico",
    "significado": "La presion de aceite del motor esta por debajo del nivel seguro",
    "accion": "Detener el vehiculo en cuanto sea seguro y apagar el motor. No seguir circulando",
    "tipo": "Requiere taller",
    "producto": "",
    "validoPara": "Universal"
  },
  {
    "id": "003",
    "nombre": "Nivel de aceite bajo",
    "categoria": "Motor",
    "color": "Ambar",
    "gravedad": "Atencion",
    "significado": "El nivel de aceite del motor esta por debajo del minimo (distinto de la presion)",
    "accion": "Comprobar nivel con la varilla y rellenar con el aceite adecuado",
    "tipo": "Solucionable",
    "producto": "Aceite de motor",
    "validoPara": "Universal"
  },
  {
    "id": "004",
    "nombre": "Temperatura del motor alta",
    "categoria": "Motor",
    "color": "Rojo",
    "gravedad": "Critico",
    "significado": "El motor se esta sobrecalentando",
    "accion": "Parar en cuanto sea posible, apagar el motor y dejar enfriar. No abrir el radiador en caliente",
    "tipo": "Requiere taller",
    "producto": "",
    "validoPara": "Universal"
  },
  {
    "id": "005",
    "nombre": "Liquido refrigerante bajo",
    "categoria": "Motor",
    "color": "Ambar",
    "gravedad": "Atencion",
    "significado": "El nivel de liquido refrigerante esta por debajo del minimo",
    "accion": "Rellenar con refrigerante adecuado cuando el motor este frio",
    "tipo": "Solucionable",
    "producto": "Liquido refrigerante",
    "validoPara": "Universal"
  },
  {
    "id": "006",
    "nombre": "Precalentamiento diesel",
    "categoria": "Motor",
    "color": "Naranja",
    "gravedad": "Informativo",
    "significado": "Las bujias de precalentamiento estan activas antes del arranque en frio",
    "accion": "Esperar a que el testigo se apague antes de arrancar",
    "tipo": "Informativo",
    "producto": "",
    "validoPara": "Solo diesel"
  },
  {
    "id": "007",
    "nombre": "Filtro de particulas (DPF) saturado",
    "categoria": "Motor",
    "color": "Ambar",
    "gravedad": "Atencion",
    "significado": "El filtro de particulas diesel esta saturado de hollin",
    "accion": "Circular por carretera a mayor regimen para forzar la regeneracion. Si persiste, ir a taller",
    "tipo": "Requiere taller",
    "producto": "",
    "validoPara": "Solo diesel"
  },
  {
    "id": "008",
    "nombre": "Turbo (sobrepresion o fallo)",
    "categoria": "Motor",
    "color": "Ambar",
    "gravedad": "Atencion",
    "significado": "Fallo detectado en el sistema de sobrealimentacion (turbo)",
    "accion": "Reducir exigencia al motor y acudir a taller pronto",
    "tipo": "Requiere taller",
    "producto": "",
    "validoPara": "Depende del modelo"
  },
  {
    "id": "009",
    "nombre": "AdBlue bajo / SCR",
    "categoria": "Motor",
    "color": "Ambar",
    "gravedad": "Atencion",
    "significado": "El deposito de AdBlue esta bajo o el sistema anticontaminacion SCR falla",
    "accion": "Rellenar AdBlue cuanto antes, el motor puede limitar potencia o no arrancar si se agota",
    "tipo": "Solucionable",
    "producto": "AdBlue (liquido de escape diesel)",
    "validoPara": "Solo diesel Euro6"
  },
  {
    "id": "010",
    "nombre": "Filtro de gasolina / agua en el gasoil",
    "categoria": "Motor",
    "color": "Ambar",
    "gravedad": "Atencion",
    "significado": "Se ha detectado agua o suciedad en el filtro de combustible",
    "accion": "Acudir a taller para purgar o sustituir el filtro",
    "tipo": "Requiere taller",
    "producto": "",
    "validoPara": "Solo diesel"
  },
  {
    "id": "011",
    "nombre": "Sistema Start-Stop (fallo o desactivado)",
    "categoria": "Motor",
    "color": "Verde",
    "gravedad": "Informativo",
    "significado": "El sistema de parada y arranque automatico esta desactivado o con fallo",
    "accion": "Si es un fallo, revisar en proxima visita al taller",
    "tipo": "Informativo",
    "producto": "",
    "validoPara": "Universal"
  },
  {
    "id": "012",
    "nombre": "Nivel de combustible bajo",
    "categoria": "Combustible Y Autonomia",
    "color": "Ambar",
    "gravedad": "Atencion",
    "significado": "Queda poco combustible en el deposito",
    "accion": "Repostar en cuanto sea posible",
    "tipo": "Informativo",
    "producto": "",
    "validoPara": "Universal"
  },
  {
    "id": "013",
    "nombre": "Tapon de combustible mal cerrado",
    "categoria": "Combustible Y Autonomia",
    "color": "Ambar",
    "gravedad": "Informativo",
    "significado": "El tapon del deposito no esta bien cerrado",
    "accion": "Revisar y cerrar correctamente el tapon",
    "tipo": "Informativo",
    "producto": "Tapon de combustible de repuesto",
    "validoPara": "Universal"
  },
  {
    "id": "014",
    "nombre": "Autonomia baja (electrico/hibrido)",
    "categoria": "Combustible Y Autonomia",
    "color": "Ambar",
    "gravedad": "Atencion",
    "significado": "Queda poca autonomia de bateria para continuar circulando",
    "accion": "Buscar punto de carga cercano",
    "tipo": "Informativo",
    "producto": "",
    "validoPara": "Electricos e hibridos"
  },
  {
    "id": "015",
    "nombre": "Freno de mano / estacionamiento puesto",
    "categoria": "Frenos",
    "color": "Rojo",
    "gravedad": "Informativo",
    "significado": "El freno de mano o de estacionamiento esta activado",
    "accion": "Desactivar el freno de mano antes de circular",
    "tipo": "Informativo",
    "producto": "",
    "validoPara": "Universal"
  },
  {
    "id": "016",
    "nombre": "Liquido de frenos bajo",
    "categoria": "Frenos",
    "color": "Rojo",
    "gravedad": "Critico",
    "significado": "El nivel de liquido de frenos esta por debajo del minimo",
    "accion": "No circular hasta revisar, riesgo de perdida de frenada",
    "tipo": "Solucionable",
    "producto": "Liquido de frenos DOT4",
    "validoPara": "Universal"
  },
  {
    "id": "017",
    "nombre": "Pastillas de freno desgastadas",
    "categoria": "Frenos",
    "color": "Ambar",
    "gravedad": "Atencion",
    "significado": "Las pastillas de freno estan cerca del limite de desgaste",
    "accion": "Programar revision de frenos pronto, evitar frenadas bruscas innecesarias",
    "tipo": "Solucionable",
    "producto": "Pastillas de freno",
    "validoPara": "Depende del modelo"
  },
  {
    "id": "018",
    "nombre": "ABS (antibloqueo de frenos)",
    "categoria": "Frenos",
    "color": "Ambar",
    "gravedad": "Atencion",
    "significado": "Fallo en el sistema antibloqueo de frenos",
    "accion": "El frenado normal sigue funcionando pero sin asistencia ABS. Acudir a taller pronto",
    "tipo": "Requiere taller",
    "producto": "",
    "validoPara": "Universal"
  },
  {
    "id": "019",
    "nombre": "Sistema de frenos general",
    "categoria": "Frenos",
    "color": "Rojo",
    "gravedad": "Critico",
    "significado": "Fallo grave detectado en el sistema de frenado",
    "accion": "Parar con precaucion y no seguir circulando, riesgo de perdida total de frenos",
    "tipo": "Requiere taller",
    "producto": "",
    "validoPara": "Universal"
  },
  {
    "id": "020",
    "nombre": "Freno de estacionamiento electronico (fallo)",
    "categoria": "Frenos",
    "color": "Ambar",
    "gravedad": "Atencion",
    "significado": "Fallo en el freno de mano electronico",
    "accion": "Acudir a taller, evitar depender solo del freno de mano en pendientes",
    "tipo": "Requiere taller",
    "producto": "",
    "validoPara": "Depende del modelo"
  },
  {
    "id": "021",
    "nombre": "Presion de neumaticos baja (TPMS)",
    "categoria": "Neumaticos",
    "color": "Ambar",
    "gravedad": "Atencion",
    "significado": "Uno o varios neumaticos tienen presion por debajo de la recomendada",
    "accion": "Comprobar la presion en cuanto puedas y ajustar segun manual del vehiculo",
    "tipo": "Solucionable",
    "producto": "Inflador de neumaticos / manometro digital",
    "validoPara": "Universal"
  },
  {
    "id": "022",
    "nombre": "Sensor de presion de neumaticos (fallo)",
    "categoria": "Neumaticos",
    "color": "Ambar",
    "gravedad": "Atencion",
    "significado": "El sistema TPMS no puede leer correctamente la presion",
    "accion": "Revisar sensores en taller, especialmente tras cambio de neumaticos",
    "tipo": "Requiere taller",
    "producto": "",
    "validoPara": "Depende del modelo"
  },
  {
    "id": "023",
    "nombre": "Pinchazo / perdida rapida de presion",
    "categoria": "Neumaticos",
    "color": "Rojo",
    "gravedad": "Critico",
    "significado": "Perdida rapida de presion en un neumatico, posible pinchazo",
    "accion": "Reducir velocidad y parar en lugar seguro cuanto antes",
    "tipo": "Solucionable",
    "producto": "Kit antipinchazos / rueda de repuesto",
    "validoPara": "Universal"
  },
  {
    "id": "024",
    "nombre": "Bateria / alternador",
    "categoria": "Electrico Y Bateria",
    "color": "Rojo",
    "gravedad": "Critico",
    "significado": "El sistema de carga de la bateria no esta funcionando correctamente",
    "accion": "Puedes seguir con precaucion hasta un taller, evita apagar el motor si es posible",
    "tipo": "Solucionable",
    "producto": "Bateria de coche / correa de alternador",
    "validoPara": "Universal"
  },
  {
    "id": "025",
    "nombre": "Fallo del sistema electrico general",
    "categoria": "Electrico Y Bateria",
    "color": "Ambar",
    "gravedad": "Atencion",
    "significado": "Se ha detectado una anomalia electrica general en el vehiculo",
    "accion": "Acudir a taller para diagnostico",
    "tipo": "Requiere taller",
    "producto": "",
    "validoPara": "Universal"
  },
  {
    "id": "026",
    "nombre": "Direccion asistida electrica (EPS)",
    "categoria": "Direccion",
    "color": "Ambar",
    "gravedad": "Atencion",
    "significado": "Fallo en el sistema de direccion asistida electrica",
    "accion": "La direccion sera mas dura pero funcional. Acudir a taller pronto",
    "tipo": "Requiere taller",
    "producto": "",
    "validoPara": "Universal"
  },
  {
    "id": "027",
    "nombre": "Direccion asistida hidraulica (nivel de liquido)",
    "categoria": "Direccion",
    "color": "Ambar",
    "gravedad": "Atencion",
    "significado": "Nivel bajo de liquido de la direccion asistida hidraulica",
    "accion": "Revisar y rellenar nivel de liquido de direccion",
    "tipo": "Solucionable",
    "producto": "Liquido de direccion asistida",
    "validoPara": "Depende del modelo"
  },
  {
    "id": "028",
    "nombre": "Bloqueo de direccion",
    "categoria": "Direccion",
    "color": "Rojo",
    "gravedad": "Critico",
    "significado": "El sistema antirrobo ha bloqueado la columna de direccion",
    "accion": "Seguir el procedimiento de desbloqueo del manual, si persiste acudir a taller",
    "tipo": "Requiere taller",
    "producto": "",
    "validoPara": "Universal"
  },
  {
    "id": "029",
    "nombre": "Fallo de caja de cambios automatica",
    "categoria": "Transmision",
    "color": "Ambar",
    "gravedad": "Atencion",
    "significado": "Se ha detectado un fallo en la transmision automatica",
    "accion": "Reducir uso y acudir a taller lo antes posible",
    "tipo": "Requiere taller",
    "producto": "",
    "validoPara": "Automaticos"
  },
  {
    "id": "030",
    "nombre": "Sobrecalentamiento de la transmision",
    "categoria": "Transmision",
    "color": "Rojo",
    "gravedad": "Critico",
    "significado": "La caja de cambios se esta sobrecalentando",
    "accion": "Parar y dejar enfriar, evitar remolcar o forzar el vehiculo",
    "tipo": "Requiere taller",
    "producto": "",
    "validoPara": "Automaticos"
  },
  {
    "id": "031",
    "nombre": "Embrague (sistemas automatizados)",
    "categoria": "Transmision",
    "color": "Ambar",
    "gravedad": "Atencion",
    "significado": "Fallo detectado en el embrague automatizado",
    "accion": "Acudir a taller, evitar arrancadas bruscas",
    "tipo": "Requiere taller",
    "producto": "",
    "validoPara": "Depende del modelo"
  },
  {
    "id": "032",
    "nombre": "Airbag / SRS",
    "categoria": "Seguridad Y Asistencia A La Conduccion",
    "color": "Rojo",
    "gravedad": "Critico",
    "significado": "Fallo detectado en el sistema de airbags",
    "accion": "Acudir a un taller especializado lo antes posible, el airbag podria no activarse en un accidente",
    "tipo": "Requiere taller",
    "producto": "",
    "validoPara": "Universal"
  },
  {
    "id": "033",
    "nombre": "Cinturon de seguridad no abrochado",
    "categoria": "Seguridad Y Asistencia A La Conduccion",
    "color": "Rojo",
    "gravedad": "Informativo",
    "significado": "Recuerda que el cinturon de seguridad no esta abrochado",
    "accion": "Abrochar el cinturon antes de circular",
    "tipo": "Informativo",
    "producto": "",
    "validoPara": "Universal"
  },
  {
    "id": "034",
    "nombre": "Control de estabilidad (ESP)",
    "categoria": "Seguridad Y Asistencia A La Conduccion",
    "color": "Ambar",
    "gravedad": "Atencion",
    "significado": "Fallo en el sistema de control de estabilidad",
    "accion": "Acudir a taller, el vehiculo pierde parte de su estabilidad en curvas o suelo resbaladizo",
    "tipo": "Requiere taller",
    "producto": "",
    "validoPara": "Universal"
  },
  {
    "id": "035",
    "nombre": "ESP desactivado manualmente",
    "categoria": "Seguridad Y Asistencia A La Conduccion",
    "color": "Ambar",
    "gravedad": "Informativo",
    "significado": "El control de estabilidad ha sido desactivado por el conductor",
    "accion": "Ninguna accion si fue intencionado, se puede reactivar en cualquier momento",
    "tipo": "Informativo",
    "producto": "",
    "validoPara": "Universal"
  },
  {
    "id": "036",
    "nombre": "Control de traccion (ASR/TCS)",
    "categoria": "Seguridad Y Asistencia A La Conduccion",
    "color": "Ambar",
    "gravedad": "Atencion",
    "significado": "Fallo en el sistema de control de traccion",
    "accion": "Circular con precaucion, especialmente en suelo mojado o resbaladizo",
    "tipo": "Requiere taller",
    "producto": "",
    "validoPara": "Universal"
  },
  {
    "id": "037",
    "nombre": "Asistente de mantenimiento de carril (LKA)",
    "categoria": "Seguridad Y Asistencia A La Conduccion",
    "color": "Ambar",
    "gravedad": "Informativo",
    "significado": "Fallo o desactivacion del asistente de mantenimiento de carril",
    "accion": "Revisar en taller si el fallo persiste, no es critico para conducir",
    "tipo": "Requiere taller",
    "producto": "",
    "validoPara": "Depende del modelo"
  },
  {
    "id": "038",
    "nombre": "Frenada autonoma de emergencia (AEB)",
    "categoria": "Seguridad Y Asistencia A La Conduccion",
    "color": "Ambar",
    "gravedad": "Atencion",
    "significado": "Fallo en el sistema de frenada automatica de emergencia",
    "accion": "Acudir a taller, se pierde esta asistencia de seguridad activa",
    "tipo": "Requiere taller",
    "producto": "",
    "validoPara": "Depende del modelo"
  },
  {
    "id": "039",
    "nombre": "Alerta de colision frontal / distancia de seguridad",
    "categoria": "Seguridad Y Asistencia A La Conduccion",
    "color": "Ambar",
    "gravedad": "Informativo",
    "significado": "Aviso de que la distancia con el vehiculo de delante es reducida",
    "accion": "Aumentar la distancia de seguridad",
    "tipo": "Informativo",
    "producto": "",
    "validoPara": "Depende del modelo"
  },
  {
    "id": "040",
    "nombre": "Detector de fatiga del conductor",
    "categoria": "Seguridad Y Asistencia A La Conduccion",
    "color": "Ambar",
    "gravedad": "Informativo",
    "significado": "El sistema ha detectado signos de cansancio en la conduccion",
    "accion": "Considerar parar a descansar",
    "tipo": "Informativo",
    "producto": "",
    "validoPara": "Depende del modelo"
  },
  {
    "id": "041",
    "nombre": "Airbag pasajero desactivado",
    "categoria": "Seguridad Y Asistencia A La Conduccion",
    "color": "Verde",
    "gravedad": "Informativo",
    "significado": "El airbag del asiento del pasajero esta desactivado (normalmente por sillita infantil)",
    "accion": "Ninguna accion si es intencionado",
    "tipo": "Informativo",
    "producto": "",
    "validoPara": "Universal"
  },
  {
    "id": "042",
    "nombre": "Sensor de aparcamiento (fallo)",
    "categoria": "Seguridad Y Asistencia A La Conduccion",
    "color": "Ambar",
    "gravedad": "Informativo",
    "significado": "Fallo en el sistema de sensores de aparcamiento",
    "accion": "No es critico, pero se pierde la asistencia al aparcar. Revisar cuando puedas",
    "tipo": "Requiere taller",
    "producto": "",
    "validoPara": "Depende del modelo"
  },
  {
    "id": "043",
    "nombre": "Camara trasera (fallo)",
    "categoria": "Seguridad Y Asistencia A La Conduccion",
    "color": "Ambar",
    "gravedad": "Informativo",
    "significado": "Fallo en la camara de vision trasera",
    "accion": "Revisar en taller, mientras tanto usar los espejos con mas atencion",
    "tipo": "Requiere taller",
    "producto": "",
    "validoPara": "Depende del modelo"
  },
  {
    "id": "044",
    "nombre": "Asistente de arranque en pendiente (Hill Start Assist)",
    "categoria": "Seguridad Y Asistencia A La Conduccion",
    "color": "Ambar",
    "gravedad": "Informativo",
    "significado": "Fallo en el asistente que evita que el coche retroceda al arrancar en cuesta",
    "accion": "Circular con precaucion en pendientes hasta revisar",
    "tipo": "Requiere taller",
    "producto": "",
    "validoPara": "Depende del modelo"
  },
  {
    "id": "045",
    "nombre": "Control de descenso en pendientes (Hill Descent Control)",
    "categoria": "Seguridad Y Asistencia A La Conduccion",
    "color": "Ambar",
    "gravedad": "Informativo",
    "significado": "Fallo en el sistema de control de velocidad en bajadas pronunciadas",
    "accion": "Circular con precaucion en descensos, usando el freno de forma manual",
    "tipo": "Requiere taller",
    "producto": "",
    "validoPara": "Todoterrenos y SUV"
  },
  {
    "id": "046",
    "nombre": "Traccion integral / 4x4 (fallo)",
    "categoria": "Suspension Y Traccion",
    "color": "Ambar",
    "gravedad": "Atencion",
    "significado": "Fallo detectado en el sistema de traccion a las cuatro ruedas",
    "accion": "El vehiculo puede pasar a traccion simple. Acudir a taller pronto",
    "tipo": "Requiere taller",
    "producto": "",
    "validoPara": "Vehiculos 4x4"
  },
  {
    "id": "047",
    "nombre": "Bloqueo diferencial activado",
    "categoria": "Suspension Y Traccion",
    "color": "Verde",
    "gravedad": "Informativo",
    "significado": "Indica que el bloqueo del diferencial esta activado",
    "accion": "Ninguna accion necesaria, desactivar al volver a asfalto normal",
    "tipo": "Informativo",
    "producto": "",
    "validoPara": "Todoterrenos"
  },
  {
    "id": "048",
    "nombre": "Suspension neumatica (fallo)",
    "categoria": "Suspension Y Traccion",
    "color": "Ambar",
    "gravedad": "Atencion",
    "significado": "Fallo detectado en el sistema de suspension neumatica",
    "accion": "Acudir a taller, el vehiculo puede circular pero con la suspension mas rigida o mas baja de lo normal",
    "tipo": "Requiere taller",
    "producto": "",
    "validoPara": "Depende del modelo"
  },
  {
    "id": "049",
    "nombre": "Luces de posicion encendidas",
    "categoria": "Iluminacion",
    "color": "Verde",
    "gravedad": "Informativo",
    "significado": "Indica que las luces de posicion estan encendidas",
    "accion": "Ninguna accion necesaria",
    "tipo": "Informativo",
    "producto": "",
    "validoPara": "Universal"
  },
  {
    "id": "050",
    "nombre": "Luces de cruce encendidas",
    "categoria": "Iluminacion",
    "color": "Verde",
    "gravedad": "Informativo",
    "significado": "Indica que las luces de cruce (cortas) estan encendidas",
    "accion": "Ninguna accion necesaria",
    "tipo": "Informativo",
    "producto": "",
    "validoPara": "Universal"
  },
  {
    "id": "051",
    "nombre": "Luces largas encendidas",
    "categoria": "Iluminacion",
    "color": "Azul",
    "gravedad": "Informativo",
    "significado": "Indica que las luces largas estan activadas",
    "accion": "Recordar bajarlas al cruzarte con otros vehiculos",
    "tipo": "Informativo",
    "producto": "",
    "validoPara": "Universal"
  },
  {
    "id": "052",
    "nombre": "Antinieblas delanteras",
    "categoria": "Iluminacion",
    "color": "Verde",
    "gravedad": "Informativo",
    "significado": "Indica que las luces antiniebla delanteras estan encendidas",
    "accion": "Ninguna accion necesaria, apagar si ya no hay niebla",
    "tipo": "Informativo",
    "producto": "",
    "validoPara": "Universal"
  },
  {
    "id": "053",
    "nombre": "Antinieblas traseras",
    "categoria": "Iluminacion",
    "color": "Ambar",
    "gravedad": "Informativo",
    "significado": "Indica que la luz antiniebla trasera esta encendida",
    "accion": "Apagar si ya no hay niebla para no deslumbrar a otros conductores",
    "tipo": "Informativo",
    "producto": "",
    "validoPara": "Universal"
  },
  {
    "id": "054",
    "nombre": "Intermitente activado",
    "categoria": "Iluminacion",
    "color": "Verde",
    "gravedad": "Informativo",
    "significado": "Indica que el intermitente esta en funcionamiento",
    "accion": "Ninguna accion necesaria",
    "tipo": "Informativo",
    "producto": "",
    "validoPara": "Universal"
  },
  {
    "id": "055",
    "nombre": "Bombilla fundida",
    "categoria": "Iluminacion",
    "color": "Ambar",
    "gravedad": "Atencion",
    "significado": "Una de las luces exteriores no esta funcionando",
    "accion": "Revisar y sustituir la bombilla afectada",
    "tipo": "Solucionable",
    "producto": "Bombilla / kit de bombillas",
    "validoPara": "Depende del modelo"
  },
  {
    "id": "056",
    "nombre": "Luces diurnas (DRL) fallo",
    "categoria": "Iluminacion",
    "color": "Ambar",
    "gravedad": "Atencion",
    "significado": "Fallo en las luces diurnas (DRL)",
    "accion": "Revisar bombillas o modulo de luces diurnas",
    "tipo": "Solucionable",
    "producto": "Kit de luces LED diurnas",
    "validoPara": "Depende del modelo"
  },
  {
    "id": "057",
    "nombre": "Sensor de lluvia / luces automaticas (fallo)",
    "categoria": "Iluminacion",
    "color": "Ambar",
    "gravedad": "Informativo",
    "significado": "Fallo en el sensor que activa limpiaparabrisas o luces de forma automatica",
    "accion": "No es critico, se puede activar todo manualmente. Revisar en taller",
    "tipo": "Requiere taller",
    "producto": "",
    "validoPara": "Depende del modelo"
  },
  {
    "id": "058",
    "nombre": "Desempanador de luneta trasera activado",
    "categoria": "Iluminacion",
    "color": "Verde",
    "gravedad": "Informativo",
    "significado": "Indica que el desempanador de la luneta trasera esta encendido",
    "accion": "Apagar cuando el cristal ya no este empanado, consume bateria",
    "tipo": "Informativo",
    "producto": "",
    "validoPara": "Universal"
  },
  {
    "id": "059",
    "nombre": "Puerta abierta",
    "categoria": "Carroceria Y Puertas",
    "color": "Ambar",
    "gravedad": "Informativo",
    "significado": "Una puerta no esta bien cerrada",
    "accion": "Comprobar y cerrar correctamente antes de circular",
    "tipo": "Informativo",
    "producto": "",
    "validoPara": "Universal"
  },
  {
    "id": "060",
    "nombre": "Maletero abierto",
    "categoria": "Carroceria Y Puertas",
    "color": "Ambar",
    "gravedad": "Informativo",
    "significado": "El maletero no esta bien cerrado",
    "accion": "Comprobar y cerrar correctamente antes de circular",
    "tipo": "Informativo",
    "producto": "",
    "validoPara": "Universal"
  },
  {
    "id": "061",
    "nombre": "Capo abierto",
    "categoria": "Carroceria Y Puertas",
    "color": "Ambar",
    "gravedad": "Informativo",
    "significado": "El capo no esta bien cerrado",
    "accion": "Comprobar y cerrar correctamente antes de circular",
    "tipo": "Informativo",
    "producto": "",
    "validoPara": "Universal"
  },
  {
    "id": "062",
    "nombre": "Aviso de revision / mantenimiento (llave inglesa)",
    "categoria": "Mantenimiento General E Hibridos/Electricos",
    "color": "Ambar",
    "gravedad": "Informativo",
    "significado": "Aviso de mantenimiento programado segun kilometraje o tiempo",
    "accion": "Programar revision segun manual de mantenimiento",
    "tipo": "Solucionable",
    "producto": "Kit de mantenimiento / filtros",
    "validoPara": "Universal"
  },
  {
    "id": "063",
    "nombre": "Liquido limpiaparabrisas bajo",
    "categoria": "Mantenimiento General E Hibridos/Electricos",
    "color": "Ambar",
    "gravedad": "Informativo",
    "significado": "El nivel de liquido limpiaparabrisas esta por debajo del minimo",
    "accion": "Rellenar con liquido limpiaparabrisas",
    "tipo": "Solucionable",
    "producto": "Liquido limpiaparabrisas",
    "validoPara": "Universal"
  },
  {
    "id": "064",
    "nombre": "Filtro de habitaculo",
    "categoria": "Mantenimiento General E Hibridos/Electricos",
    "color": "Verde",
    "gravedad": "Informativo",
    "significado": "Aviso de sustitucion del filtro de habitaculo (polen)",
    "accion": "Sustituir el filtro, mejora la calidad del aire interior",
    "tipo": "Solucionable",
    "producto": "Filtro de habitaculo / polen",
    "validoPara": "Universal"
  },
  {
    "id": "065",
    "nombre": "Fallo del sistema hibrido",
    "categoria": "Mantenimiento General E Hibridos/Electricos",
    "color": "Ambar",
    "gravedad": "Atencion",
    "significado": "Se ha detectado un fallo en el sistema de propulsion hibrido",
    "accion": "Acudir a taller especializado en hibridos lo antes posible",
    "tipo": "Requiere taller",
    "producto": "",
    "validoPara": "Hibridos"
  },
  {
    "id": "066",
    "nombre": "Bateria de alta tension baja (hibrido/electrico)",
    "categoria": "Mantenimiento General E Hibridos/Electricos",
    "color": "Ambar",
    "gravedad": "Atencion",
    "significado": "La bateria de traccion esta con poca carga",
    "accion": "Cargar el vehiculo en un punto de carga lo antes posible",
    "tipo": "Informativo",
    "producto": "",
    "validoPara": "Electricos e hibridos"
  },
  {
    "id": "067",
    "nombre": "Fallo de carga (electrico/hibrido)",
    "categoria": "Mantenimiento General E Hibridos/Electricos",
    "color": "Ambar",
    "gravedad": "Atencion",
    "significado": "Error durante el proceso de carga de la bateria",
    "accion": "Revisar cable y punto de carga, si persiste acudir a taller especializado",
    "tipo": "Requiere taller",
    "producto": "",
    "validoPara": "Electricos e hibridos"
  }
];

module.exports = catalogo;
